# Generated by Django 4.1.7 on 2023-04-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('CGPA', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.section')),
                
            ],
        ),
    ]
