# Generated by Django 4.1.7 on 2023-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_graduation',
            field=models.IntegerField(default=1),
        ),
    ]
