# Generated by Django 4.1.7 on 2023-04-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_student_date_of_admission_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(max_length=10),
        ),
    ]
